# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PGSTripAgenda' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PGSTripAgenda
  pod 'MobileCenter/Crashes', '~> 0.12.1'
  pod 'MobileCenter/Analytics', '~> 0.12.1'
  pod 'RNMobileCenterShared', '~> 0.9.0'

  

  target 'PGSTripAgendaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PGSTripAgenda-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PGSTripAgenda-tvOS

  target 'PGSTripAgenda-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
